kind: pipeline
type: docker
name: build

clone:
  depth: 50
  tags: true
  skip_verify: true

steps:

- name: build-and-deploy
  image: plugins/docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
    - apk update
    - apk add make
    - make build
    - make deploy

volumes:
- name: dockersock
  host:
      path: /var/run/docker.sock